inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
